Style: Replace ($(...)) with readarray

diff --git a/bin/kubectl-remove-completed b/bin/kubectl-remove-completed
--- a/bin/kubectl-remove-completed
+++ b/bin/kubectl-remove-completed
@@ -2,10 +2,9 @@
 set -e # Terminate the script at first error.
 set -o pipefail
 
-IFS=$'\n'
-typeset -a completedPods=($(kubectl-completed "$@" | awk '{print $1}'))
+readarray -t completedPods < <(kubectl-completed "$@" | awk '{print $1}')
 if [ ${#completedPods[@]} -eq 0 ]; then
-    echo >&2 "ERROR: No completed PODs found."
+    echo >&2 'ERROR: No completed PODs found.'
     exit 99
 fi
 
diff --git a/bin/kubectl-remove-evicted b/bin/kubectl-remove-evicted
--- a/bin/kubectl-remove-evicted
+++ b/bin/kubectl-remove-evicted
@@ -2,10 +2,9 @@
 set -e # Terminate the script at first error.
 set -o pipefail
 
-IFS=$'\n'
-typeset -a evictedPods=($(kubectl-evicted "$@" | awk '{print $1}'))
+readarray -t evictedPods < <(kubectl-evicted "$@" | awk '{print $1}')
 if [ ${#evictedPods[@]} -eq 0 ]; then
-    echo >&2 "ERROR: No evicted PODs found."
+    echo >&2 'ERROR: No evicted PODs found.'
     exit 99
 fi
 
