kubectl-podimageages: ENH: Consistency: Implement -r|--relative-date here as well

diff --git a/bin/kubectl-podimageages b/bin/kubectl-podimageages
--- a/bin/kubectl-podimageages
+++ b/bin/kubectl-podimageages
@@ -5,7 +5,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[-v|--verbose] [KUBECTL-ARGS ...] [POD-NAME ...] [-- EXPR] [-c CONTAINER-NAME] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-r|--relative-date] [-v|--verbose] [KUBECTL-ARGS ...] [POD-NAME ...] [-- EXPR] [-c CONTAINER-NAME] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -26,21 +26,38 @@ HELPDESCRIPTION
     printShortUsage "$1"
     echo
     cat <<HELPTEXT
+    --relative-date|-r	Use relative dates (e.g. "2 days ago") instead of
+			absolute timestamps.
     --verbose|-v	Include the image names in the output.
 HELPTEXT
 }
 
+typeset -a reldate=()
 isVerbose=
 typeset -a podimagesArgs=()
 while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--relative-date|-r)
+			shift
+			if type -t reldate >/dev/null; then
+			    reldate=(reldate --date-pattern '\b(?<year>\d\d\d\d)-(?<month>\d\d)-(?<day>\d\d)T(?<hours>\d\d):(?<minutes>\d\d):(?<seconds>\d\d)(?<timezone>Z)\b' --prefer-past)
+			else
+			    echo >&2 'ERROR: The reldate command is not available.'
+			    exit 3
+			fi
+			;;
 	--verbose|-v)	shift; isVerbose=t;;
 	--)		podimagesArgs+=("$1"); shift; break;;
 	*)		podimagesArgs+=("$1"); shift;;
     esac
 done
+
+lookupImageAge()
+{
+    regctl image inspect --format '{{.Created.Format "2006-01-02T15:04:05Z07:00" }}' "$imageName"
+}
 
 typeset -A imageAges=()
 exitStatus=
@@ -68,8 +85,11 @@ do
 
     imageAge="${imageAges["$imageName"]}"
     if [ -z "$imageAge" ]; then
-	imageAge="$(regctl image inspect --format '{{.Created.Format "2006-01-02T15:04:05Z07:00" }}' "$imageName")" || imageAge='???'
-	imageAges["$imageName"]="$imageAge"
+	imageAge="$(
+	    eval 'lookupImageAge "$imageName"' \
+		    "${reldate:+|}" '"${reldate[@]}"'
+	    )"  # The age lookup takes so long that the separate launch of the reldate command shouldn't matter. At least it's not repeated for the same image.
+	imageAges["$imageName"]="${imageAge:-???}"
     fi
 
     printf '%s%s%s%s%s\n' "$indent" "$containerName" "${containerName:+$sep}" "${isVerbose:+$imageName }" "$imageAge"
